[package]
name = "exgine"
version = "0.1.0"
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]

[dependencies]

[lib]
name = "exgine"
path = "src/lib.rs"

[[example]]
name = "robot_mission"
path = "examples/robot_mission/robot_mission.rs"