[package]
authors = ["Alex Rozgo <alex.rozgo@gmail.com>"]
name = "exgine"
version = "0.1.0"

[dependencies]

[dev-dependencies]
uuid = "0.8.2"

[lib]
name = "exgine"
path = "src/lib.rs"

[[example]]
name = "robot_mission"
path = "examples/robot_mission/robot_mission.rs"
